services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.streamable-http
    container_name: mcp-code-runner-server
    restart: unless-stopped
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true

#Ports 3088
